---
- name: Setup users and push ssh key
  hosts: all
  become: True
  become_user: root
  
  vars:
    ansible_password: f$us#r@098
    ansible_become_password: f$us#r@098
    sudo_password: f$us#r@098
    script_src: user_setup.sh
    hostname_arg: "{{ inventory_hostname }}" 
    ssh_public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC3RWItgvuZK3rVgONZXQ3zlNF1bdn4YfR67RiUVONH9UU9B6+YwCou94y5SOZ+QTR2dWrjS6k8Yh1UDrFKjd9J8dHR4F9hcxw8O5ilfPzhttgDWoMu0Ex+HHMgy+7eOvtZAqqbeLpRocmw/LOJSDcXlRPq/ZTQvvkThjyYjM18TnhURbzDHyUB2cTmhFy8HMpioPaxdYmr7J3brKZoxn7utWayeMDEwqY47ot+exFohf0ZkAHLp5shcdNexlRgVkf2p6gMwsc/KP9tjaOeeR9QKzWYSCROTUUFZMecHnVpaoieDIGmRO5yP5t0hj7HWI0xadm/Nw/bXrtnBMToiEJw0u3H/v6vpBh80oO0xnY4xuOxZAX7TOjnjOKkUvAHEHv4vASw1F2wowFYysN3BIlWmOtP4HJxdi8VJqXlIVH8tO4v/yE8dYTm5KVoohKMX0YiHvxKWgtrF907WBEINOnLVlN0E0GjvU3fiDaSkpSfyQolgvtMhdj2/07IeAXwOuLhd4ZWkdxy67iJ5Qdyc42JeTG1sx1sUUAF4BZNf+s64aK9jsky2hX9yxKhMcmydsS3bLYHCsaEiKNyuVcC2nyWdOj6xqKlsLsmayJer3F4VjwxelSNp1MzArvXz+vds2DXk5+wT0WavkmaSMihnblTSyTli9TpKm2LOFUYfnAsgw== fsuser@FS-SRV-IN-04"

  tasks:
    - name: Check if flag exists
      ansible.builtin.stat:
        path: /home/fsuser/user_setup.completed
      register: flag_file

    - name: Copy custom script to remote host
      ansible.builtin.copy:
        src: "{{ script_src }}"
        dest: /tmp/script.sh
        mode: "0755"
      when: flag_file.stat.exists == False

    - name: Execute script on remote host
      ansible.builtin.command:
        cmd: /tmp/script.sh "{{ hostname_arg }}"
      when: flag_file.stat.exists == False

    - name: Create flag file if script was executed
      ansible.builtin.file:
        path: /home/fsuser/user_setup.completed
        state: touch
      when: flag_file.stat.exists == False

    - name: Delete script from remote host
      ansible.builtin.file:
        path: /tmp/script.sh
        state: absent
      when: flag_file.stat.exists == False

    - name: Ensure .ssh directory exists
      ansible.builtin.file:
        path: /home/fsuser/.ssh
        state: directory
        mode: '0700'
        owner: fsuser
        group: fsuser

    - name: Create authorized_keys file if it doesn't exist
      ansible.builtin.file:
        path: /home/fsuser/.ssh/authorized_keys
        state: touch
        owner: fsuser
        group: fsuser
        mode: '0600'

    - name: Add SSH public key to authorized_keys
      ansible.builtin.lineinfile:
        path: /home/fsuser/.ssh/authorized_keys
        line: "{{ ssh_public_key }}"
        create: yes
        owner: fsuser
        group: fsuser
        mode: '0600'

    - name: Ensure correct permissions for .ssh directory and authorized_keys file
      ansible.builtin.command:
        cmd: |
          chown -R fsuser:fsuser /home/fsuser/.ssh
          chmod 700 /home/fsuser/.ssh
          chmod 600 /home/fsuser/.ssh/authorized_keys
