---
- name: Install Postman using Snap
  hosts: 192.168.1.5
  become: true
  tasks:

    - name: Ensure snapd is installed
      ansible.builtin.apt:
        name: snapd
        state: present
        update_cache: yes

    - name: Install Postman using Snap
      ansible.builtin.snap:
        name: postman
        state: present
