---
- name: Install Android Studio on Ubuntu
  hosts: all
  become: yes
  tasks:

    # Step 1: Gather facts about the system
    - name: Gathering Facts
      ansible.builtin.setup:

    # Step 2: Update apt packages
    - name: Update apt packages
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600  # Cache valid for 1 hour

    # Step 3: Install required dependencies
    - name: Install required dependencies
      ansible.builtin.apt:
        name:
          - openjdk-11-jdk
          - unzip
          - wget
        state: present

    # Step 4: Download Android Studio
    - name: Download Android Studio
      ansible.builtin.get_url:
        url: "https://dl.google.com/dl/android/studio/ide-zips/2021.1.1.22/android-studio-2021.1.1.22-linux.tar.gz"
        dest: "/tmp/android-studio.tar.gz"
        mode: '0644'

    # Step 5: Check if Android Studio tarball exists
    - name: Check if the Android Studio tarball exists
      ansible.builtin.stat:
        path: "/tmp/android-studio.tar.gz"
      register: android_studio_tar

    # Debugging Step: Confirm if the file was downloaded
    - name: Debugging output
      ansible.builtin.debug:
        msg: "The file exists: {{ android_studio_tar.stat.exists }}"

    # Step 6: Fail if the Android Studio tar.gz file doesn't exist
    - name: Fail if the Android Studio tar.gz file doesn't exist
      ansible.builtin.fail:
        msg: "Android Studio tar.gz file not found!"
      when: android_studio_tar.stat.exists == false

    # Step 7: Extract Android Studio tar.gz file
    - name: Extract Android Studio
      ansible.builtin.unarchive:
        src: "/tmp/android-studio.tar.gz"
        dest: "/opt/"
        remote_src: yes
        creates: "/opt/android-studio"
        
    # Step 8: Set up the Android Studio environment
    - name: Set up environment variables
      ansible.builtin.lineinfile:
        path: "/etc/environment"
        line: "ANDROID_STUDIO_HOME=/opt/android-studio"
        create: yes

    # Step 9: Create a symlink for Android Studio executable
    - name: Create symlink for android studio
      ansible.builtin.file:
        src: "/opt/android-studio/bin/studio.sh"
        dest: "/usr/local/bin/android-studio"
        state: link

    # Step 10: Install additional Android Studio dependencies
    - name: Install additional dependencies for Android Studio
      ansible.builtin.apt:
        name:
          - lib32z1
          - lib32ncurses6
          - lib32stdc++6
        state: present

    # Step 11: Clean up temporary files
    - name: Clean up the downloaded tarball
      ansible.builtin.file:
        path: "/tmp/android-studio.tar.gz"
        state: absent

    # Step 12: Inform user to run Android Studio
    - name: Display success message
      ansible.builtin.debug:
        msg: "Android Studio installation completed! You can now run it using the command 'android-studio'."
