- name: Install Postman using Snap
  hosts: localhost
  become: true
  tasks:

    - name: Ensure snapd is installed
      ansible.builtin.apt:
        name: snapd
        state: present
        update_cache: yes

    - name: Install Postman using Snap
      ansible.builtin.snap:
        name: postman
        state: present
        force: yes  # Ensures reinstallation if the package already exists
