---
- name: Create 'ansible' user and grant sudo privileges
  hosts: all
  become: true  # Use 'sudo' for the following tasks
  tasks:
    - name: Create the 'ansible' user with password
      user:
        name: ansible
        password: "{{ 'finsurge@123' | password_hash('sha512') }}"
        shell: /bin/bash
        state: present

    - name: Add 'ansible' to the sudo group
      user:
        name: ansible
        groups: sudo
        append: yes
