---
- name: Install Postman via Snap
  hosts: all
  become: yes
  vars:
    ansible_user: "fsuser"  # SSH username
    ansible_ssh_pass: "f$us#r@098"  # SSH password
    ansible_ssh_extra_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"  # Disable host key checking

  tasks:
    - name: Install Snapd if not already installed
      apt:
        name: snapd
        state: present
        update_cache: yes
      when: ansible_facts.packages.snapd is not defined

    - name: Install Postman using Snap
      snap:
        name: postman
        state: present

    - name: Verify Postman Installation
      command: postman --version
      register: postman_version
      failed_when: postman_version.rc != 0

    - name: Show Postman version
      debug:
        var: postman_version.stdout
