---
- name: Create ansible user and configure SSH access
  hosts: all
  become: true
  vars:
    remote_user: fsuser
    remote_user_password: "f$us#r@098"
    ansible_user_password: "finsurge@123"
    public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC3RWItgvuZK3rVgONZXQ3zlNF1bdn4YfR67RiUVONH9UU9B6+YwCou94y5SOZ+QTR2dWrjS6k8Yh1UDrFKjd9J8dHR4F9hcxw8O5ilfPzhttgDWoMu0Ex+HHMgy+7eOvtZAqqbeLpRocmw/LOJSDcXlRPq/ZTQvvkThjyYjM18TnhURbzDHyUB2cTmhFy8HMpioPaxdYmr7J3brKZoxn7utWayeMDEwqY47ot+exFohf0ZkAHLp5shcdNexlRgVkf2p6gMwsc/KP9tjaOeeR9QKzWYSCROTUUFZMecHnVpaoieDIGmRO5yP5t0hj7HWI0xadm/Nw/bXrtnBMToiEJw0u3H/v6vpBh80oO0xnY4xuOxZAX7TOjnjOKkUvAHEHv4vASw1F2wowFYysN3BIlWmOtP4HJxdi8VJqXlIVH8tO4v/yE8dYTm5KVoohKMX0YiHvxKWgtrF907WBEINOnLVlN0E0GjvU3fiDaSkpSfyQolgvtMhdj2/07IeAXwOuLhd4ZWkdxy67iJ5Qdyc42JeTG1sx1sUUAF4BZNf+s64aK9jsky2hX9yxKhMcmydsS3bLYHCsaEiKNyuVcC2nyWdOj6xqKlsLsmayJer3F4VjwxelSNp1MzArvXz+vds2DXk5+wT0WavkmaSMihnblTSyTli9TpKm2LOFUYfnAsgw== fsuser@FS-SRV-IN-04"

  tasks:
    - name: Ensure ansible user exists
      user:
        name: ansible
        password: "{{ ansible_user_password | password_hash('sha512') }}"
        shell: /bin/bash
        state: present
        create_home: true
        groups: sudo

    - name: Debug user existence
      command: getent passwd ansible

    - name: Set ownership of ansible home directory
      file:
        path: /home/ansible
        owner: ansible
        group: ansible
        state: directory
        recurse: true

    - name: Wait for the system to recognize ansible user
      wait_for:
        path: /home/ansible
        timeout: 10

    - name: Create .ssh directory for ansible user
      file:
        path: /home/ansible/.ssh
        state: directory
        owner: ansible
        group: ansible
        mode: '0700'

    - name: Copy public key to authorized_keys
      copy:
        content: "{{ public_key }}"
        dest: /home/ansible/.ssh/authorized_keys
        owner: ansible
        group: ansible
        mode: '0600'

    - name: Verify SSH configuration
      debug:
        msg: "Public key successfully copied to /home/ansible/.ssh/authorized_keys"
