---
- name: Create a user with sudo privileges and add SSH key
  remote_user: root
  hosts: all
  become: true  # Ensure this is set to run tasks with elevated privileges
  tasks:
    - name: Create a new user
      user:
        name: ansible
        state: present
        shell: /bin/bash

    - name: Add user to sudo group
      user:
        name: ansible
        groups: sudo
        append: yes

    - name: Allow passwordless sudo for the user (Debian/Ubuntu)
      lineinfile:
        path: /etc/sudoers
        line: "ansible ALL=(ALL) NOPASSWD: ALL"
        validate: '/usr/sbin/visudo -cf %s'

    - name: Ensure .ssh directory exists for ansible user
      file:
        path: "/home/ansible/.ssh"
        state: directory
        mode: 0700
      become: yes
      become_user: ansible

    - name: Add SSH public key to authorized_keys
      authorized_key:
        user: ansible
        state: present
        key: "{{ lookup('file', '/path/to/your/ssh/public_key') }}"
      become: yes
      become_user: ansible
