---
- name: Become fsuser, create ansible user and give sudo privileges
  hosts: all
  become: true
  become_user: fsuser  # Become fsuser user
  tasks:
    - name: Create ansible user
      user:
        name: ansible_user
        state: present
        shell: /bin/bash

    - name: Set password for ansible user
      user:
        name: ansible_user
        password: "{{ 'ansible_password' | password_hash('sha512') }}"

    - name: Add ansible user to sudoers file
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^ansible_user'
        line: 'ansible_user ALL=(ALL) NOPASSWD: ALL'
        validate: '/usr/sbin/visudo -cf %s'
