---
- name: Create a user with sudo privileges and add SSH key
  hosts: all
  become: yes
  tasks:
    # Ensure the 'ansible' user and group exist
    - name: Ensure ansible group exists
      group:
        name: ansible
        state: present

    - name: Ensure ansible user exists
      user:
        name: ansible
        group: ansible
        password: "{{ 'finsurge@123' | password_hash('sha512') }}"
        shell: /bin/bash
        state: present

    - name: Add user to sudo group
      user:
        name: ansible
        groups: sudo
        append: yes

    - name: Allow passwordless sudo for the user (Debian/Ubuntu)
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^ansible'
        line: 'ansible ALL=(ALL) NOPASSWD:ALL'
        validate: '/usr/sbin/visudo -cf %s'

    - name: Ensure .ssh directory exists for ansible user
      file:
        path: /home/ansible/.ssh
        state: directory
        owner: ansible
        group: ansible
        mode: '0700'

    - name: Add SSH public key to authorized_keys
      copy:
        content: "{{ ansible_ssh_key }}"
        dest: /home/ansible/.ssh/authorized_keys
        owner: ansible
        group: ansible
        mode: '0600'

    # Optional: Disable strict host key checking temporarily (only for debugging)
    - name: Disable strict host key checking for SSH (temporary for debugging)
      lineinfile:
        path: /etc/ssh/ssh_config
        regexp: '^#   StrictHostKeyChecking ask'
        line: 'StrictHostKeyChecking no'
