---
- name: Create a user with sudo privileges using fsuser
  hosts: all
  become: yes
  vars:
    ansible_user: fsuser
    ansible_ssh_pass: f$us#r@098
  tasks:
    - name: Create a new user
      user:
        name: ansible
        password: "{{ 'finsurge@123' | password_hash('sha512') }}"
        shell: /bin/bash
        state: present

    - name: Add user to sudo group
      user:
        name: ansible
        groups: sudo
        append: yes

    - name: Allow passwordless sudo for the user (Debian/Ubuntu)
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^ansible'
        line: 'ansible ALL=(ALL) NOPASSWD:ALL'
        validate: '/usr/sbin/visudo -cf %s'
