---
- name: Create a user with sudo privileges and add SSH key
  hosts: all
  become: yes
  become_user: root  # Ensure the tasks run as root

  tasks:
    - name: Create a new user
      user:
        name: ansible
        password: "{{ 'finsurge@123' | password_hash('sha512') }}"
        shell: /bin/bash
        state: present

    - name: Add user to sudo group
      user:
        name: ansible
        groups: sudo
        append: yes

    - name: Allow passwordless sudo for the user (Debian/Ubuntu)
      ansible.builtin.sudoers:
        name: ansible
        state: present
        options: 'NOPASSWD:ALL'
    
    - name: Ensure .ssh directory exists for ansible user
      file:
        path: /home/ansible/.ssh
        state: directory
        owner: ansible
        group: ansible
        mode: '0700'

    - name: Add SSH public key to authorized_keys
      copy:
        content: |
          ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCYRVadvilhikBIJZ14OQiMB/nts5db3kXSlOBfl2z49gq1PnGjBLFG5/4m3qTlfPLe+R00R6fMIgFqh75t0MMpCDrCoP+QffzijkecBhfBAyi7/V+BuoI7xcC7B8om2MVXqMB10WiTng20vzN2sio8T/WovY1MuWtc3PyZrNa18CzV3lH+RGPCJhIelCot6KKD8dyZaiWfQ1Las9w+9aMFykSBC/uG3jMOVmOmXXYCGfRN285q6JkTP3SA/3BOar4lRWFXtde9+x3BEVqR0CxfpNHl4gLXlkbqAD0L5pnJ0FCNtzMhPLvXRuiKFpozoMs+FsffQdIknb+bKoJBEunT fsuser@FS-DEV-L-IN-045
        dest: /home/ansible/.ssh/authorized_keys
        owner: ansible
        group: ansible
        mode: '0600'

    # Optional: Disable strict host key checking temporarily (for debugging)
    - name: Disable strict host key checking for SSH (temporary for debugging)
      lineinfile:
        path: /etc/ssh/ssh_config
        regexp: '^#   StrictHostKeyChecking ask'
        line: 'StrictHostKeyChecking no'
