---
- name: Deploy portainer-ce latest
  hosts: 192.168.1.5  # Directly specifying the target host
  become: true
  become_user: "{{ lookup('env','USER') }}"  # Ensure this user has sudo privileges if needed

  tasks:
    - name: Create new volume
      community.docker.docker_volume:
        name: portainer-data

    - name: Deploy portainer
      community.docker.docker_container:
        name: portainer
        image: "docker.io/portainer/portainer-ce"
        ports:
          - "9443:9443"
        volumes:
          - /run/docker.sock:/var/run/docker.sock
          - portainer-data:/data
        restart_policy: unless-stopped

