---
- name: Installing IntelliJ IDEA Community Edition
  hosts: all
  become: True
  gather_facts: False
  
  vars:
    intellij_download_link: "https://download-cdn.jetbrains.com/idea/ideaIC-2024.1.1.tar.gz"
    intellij_installation_path: /opt

  tasks:
    - name: Download IntelliJ tarball
      ansible.builtin.get_url:
        url: "{{ intellij_download_link }}"
        dest: "/tmp/idea.tar.gz"

    - name: Extract the tar.gz file
      ansible.builtin.unarchive:
        src: "/tmp/idea.tar.gz"
        dest: "{{ intellij_installation_path }}"
        remote_src: yes

    - name: Find IntelliJ installation directory
      ansible.builtin.find:
        paths: "{{ intellij_installation_path }}"
        patterns: "idea-IC-*"
        file_type: directory
      register: intellij_dirs

    - name: Ensure IntelliJ installation directory is found
      ansible.builtin.assert:
        that:
          - intellij_dirs.matched > 0
        fail_msg: "IntelliJ installation directory not found after extraction."

    - name: Get the IntelliJ installation directory
      ansible.builtin.set_fact:
        intellij_install_dir: "{{ intellij_dirs.files[0].path }}"

    - name: Create desktop entry for IntelliJ IDEA
      ansible.builtin.copy:
        dest: /usr/share/applications/intellij.desktop
        content: |
          [Desktop Entry]
          Version=1.0
          Type=Application
          Name=IntelliJ IDEA Community Edition
          Icon={{ intellij_install_dir }}/bin/idea.svg
          Exec="{{ intellij_install_dir }}/bin/idea.sh" %f
          Comment=Capable and Ergonomic IDE for JVM
          Categories=Development;IDE;
          Terminal=false
          StartupWMClass=jetbrains-idea-ce
          StartupNotify=true
        owner: root
        group: root
        mode: "0644"

    - name: Clean up temporary files
      ansible.builtin.file:
        path: /tmp/idea.tar.gz
        state: absent
