---
- name: Password change and push ssh key
  hosts: all
  become: True
  become_user: root
  
  vars:
    ansible_password: f$us#r@098
    ansible_become_password: f$us#r@098
    sudo_password: f$us#r@098
    script_src: /ansible/scripts/password_change.sh

  tasks:

    - name: Copy custom script to remote host
      ansible.builtin.copy:
        src: "{{ script_src }}"
        dest: /tmp/script.sh
        mode: "0755"

    - name: Execute script on remote host
      ansible.builtin.command:
        cmd: /tmp/script.sh
