---
- name: Installing Postman via Snap
  hosts: all
  become: True
  gather_facts: False

  tasks:
    - name: Ensure snapd is installed
      ansible.builtin.apt:
        name: snapd
        state: present
        update_cache: yes

    - name: Ensure snapd service is running
      ansible.builtin.service:
        name: snapd
        state: started
        enabled: yes

    - name: Download and install Postman via Snap
      ansible.builtin.shell: snap install postman
      args:
        creates: "/snap/bin/postman"
      ignore_errors: True

    - name: Wait for Postman to be installed (retry logic)
      ansible.builtin.wait_for:
        path: "/snap/bin/postman"
        state: file
        timeout: 60
        delay: 5

    - name: Verify Postman installation
      ansible.builtin.command: /snap/bin/postman --version
      register: postman_version
      failed_when: false

    - name: Show Postman version (to confirm installation)
      debug:
        msg: "Postman version: {{ postman_version.stdout }}"
