---
- name: Add SSH public key to remote host using ssh-copy-id
  hosts: all  # Use all hosts defined in the inventory file
  become: false
  vars:
    ansible_user: fsuser
    ansible_ssh_pass: 'f$us#r@098'  # Provide the password here
    
  tasks:
    - name: Ensure the .ssh directory exists
      ansible.builtin.file:
        path: /home/{{ ansible_user }}/.ssh
        state: directory
        mode: '0700'

    - name: Copy public key to authorized_keys
      ansible.builtin.copy:
        src: /home/semaphore/id_rsa.pub
        dest: /home/{{ ansible_user }}/.ssh/authorized_keys
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0600'

    - name: Ensure correct permissions for authorized_keys
      ansible.builtin.file:
        path: /home/{{ ansible_user }}/.ssh/authorized_keys
        state: file
        mode: '0600'
