---
- name: Setup users and push ssh key
  hosts: all
  become: True
  become_user: fsuser

  vars:
    sudo_password: finsurge@123
    script_src: user_setup.sh
    hostname_arg: Finsurge_Inventory 
    username: fsuser
    password: finsurge@123  # Password for fsuser

  tasks:
    - name: Ensure the user fsuser exists
      ansible.builtin.user:
        name: "{{ username }}"
        state: present
        password: "{{ password | password_hash('sha512') }}"  # Ensure password is encrypted
        shell: /bin/bash
        create_home: yes

    - name: Check if flag exists
      ansible.builtin.stat:
        path: /home/{{ username }}/user_setup.completed
      register: flag_file

    - name: Copy custom script to remote host
      ansible.builtin.copy:
        src: "{{ script_src }}"
        dest: /tmp/script.sh
        mode: "0755"
      # when: flag_file.stat.exists == False

    - name: Execute script on remote host
      ansible.builtin.command:
        cmd: /tmp/script.sh "{{ hostname_arg }}"
      # when: flag_file.stat.exists == False

    - name: Create flag file if script was executed
      ansible.builtin.file:
        path: /home/{{ username }}/user_setup.completed
        state: touch
      # when: flag_file.stat.exists == False

    - name: Delete script from remote host
      ansible.builtin.file:
        path: /tmp/script.sh
        state: absent
      when: flag_file.stat.exists == False
